routes/web.php
<?php


Route::get('/', function () {
    if(Auth::guest())
    {
        return view('auth.login');
    }else{
        return redirect('/home');
    }
});

Auth::routes();

Route::group(['middleware' => ['auth', 'checkPermission']], function () {
    Route::get('/home',              'HomeController@index')->name('dashboard.index');
    Route::get('/getGraficos',       'HomeController@getGraficos')->name('dashboard.getGraficos');
    Route::resource('categorias',    'CategoriasController');
    Route::resource('helpdesk',      'HelpdeskController');
    Route::resource('empresas',      'EmpresasController');
    Route::resource('departamentos',  'DepartamentosController');
    Route::resource('perfilacesso',    'PerfisController');

    /* -------------------- HELPDESK -------------------- */
    Route::get('helpdesk/iniciarAtendimento/{id}', 'HelpdeskController@iniciarAtendimento')->name('helpdesk.iniciar_chamado');
    Route::get('helpdesk/finalizarAtendimento/{id}', 'HelpdeskController@finalizarAtendimento')->name('helpdesk.finalizar_chamado');
    Route::get('helpdesk/reabrirAtendimento/{id}', 'HelpdeskController@reabrirAtendimento')->name('helpdesk.reabrir_chamado');
    Route::post('helpdesk/inserirInteracao', 'HelpdeskController@inserirInteracao')->name('helpdesk.inserir_interacao');
    Route::get('buscarCategorias', 'HelpdeskController@buscarCategorias')->name('helpdesk.buscar_categorias');
});

app/Models/Helpdesk.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Helpdesk extends Model
{
    protected $table = 'pro_helpdesk';
    protected $primaryKey = 'helpdesk_codigo';

    protected $fillable = [
        'status_codigo',
        'credencial_codigo_cliente',
        'credencial_codigo_atendente',
        'categoria_codigo',
        'helpdesk_titulo',
        'helpdesk_detalhes',
        'prioridade_codigo'
    ];

    public function categoria(){
        return $this->belongsTo(Categorias::class, 'categoria_codigo', '');
    }

    public function cliente(){
        return $this->belongsTo(User::class, 'credencial_codigo_cliente', 'credencial_codigo');
    }

    public function atendente(){
        return $this->belongsTo(User::class, 'credencial_codigo_atendente', 'credencial_codigo');
    }

    public function status(){
        return $this->belongsTo(Status::class, 'status_codigo', '');
    }
}

app/Http/Controllers/HelpdeskController.php
<?php

namespace App\Http\Controllers;

use App\Models\Categorias;
use App\Models\Departamentos;
use App\Models\Helpdesk;
use App\Models\HelpdeskAnexos;
use App\Models\HelpdeskInteracoes;
use App\Models\Status;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Storage;

class HelpdeskController extends Controller
{
    public function index(Request $request)
    {

        $helpdesk = new Helpdesk();

        $helpdesk = $helpdesk->select(
            'pro_helpdesk.*', 'credencial_cliente.credencial_nome AS nome_cliente',
            'credencial_atendente.credencial_nome AS nome_atendente', 'pro_helpdesk_status.status_descricao', 'pro_helpdesk_status.status_classe',
            'pro_categorias.categoria_descricao', 'pro_prioridades.prioridade_grau'
        );

        $helpdesk = $helpdesk->join('pro_helpdesk_status', 'pro_helpdesk.status_codigo', '=', 'pro_helpdesk_status.status_codigo');
        $helpdesk = $helpdesk->join('pro_categorias', 'pro_helpdesk.categoria_codigo', '=', 'pro_categorias.categoria_codigo');
        $helpdesk = $helpdesk->join('pro_prioridades', 'pro_categorias.prioridade_codigo', '=', 'pro_prioridades.prioridade_codigo');
        $helpdesk = $helpdesk->leftJoin('sys_credencial AS credencial_cliente', 'pro_helpdesk.credencial_codigo_cliente', '=', 'credencial_cliente.credencial_codigo');
        $helpdesk = $helpdesk->leftJoin('sys_credencial AS credencial_atendente', 'pro_helpdesk.credencial_codigo_atendente', '=', 'credencial_atendente.credencial_codigo');

        if (isset($request->filtroNumero) && $request->filtroNumero != '') {
            $helpdesk = $helpdesk->where('pro_helpdesk.helpdesk_codigo', '=', $request->filtroNumero);
        }

        if (isset($request->filtroTitulo) && $request->filtroTitulo != '') {
            $helpdesk = $helpdesk->where('pro_helpdesk.helpdesk_titulo', 'like', '%' . $request->filtroTitulo . '%');
        }

        if (isset($request->filtroCategoria) && $request->filtroCategoria != '._.') {
            $helpdesk = $helpdesk->where('pro_helpdesk.categoria_codigo', $request->filtroCategoria);
        }

        if (isset($request->filtroStatus) && $request->filtroStatus != '._.'){
            $helpdesk = $helpdesk->where('pro_helpdesk.status_codigo', '=', $request->filtroStatus);
        }else{
            $helpdesk = $helpdesk->where('pro_helpdesk.status_codigo', '<>', 4);
        }

        if (isset($request->filtroDataIni) && $request->filtroDataIni != '') {
            $helpdesk = $helpdesk->where('pro_helpdesk.created_at', '>=', $request->filtroDataIni);
        }

        if (isset($request->filtroDataFim) && $request->filtroDataFim != '') {
            $helpdesk = $helpdesk->where('pro_helpdesk.created_at', '<=', $request->filtroDataFim);
        }

        if (isset($request->filtroDataFim) && $request->filtroDataFim != '') {
            $helpdesk = $helpdesk->where('pro_helpdesk.created_at', '<=', $request->filtroDataFim);
        }

        if (isset($request->filtroCliente) && $request->filtroCliente != '._.') {
            $helpdesk = $helpdesk->where('pro_helpdesk.credencial_codigo_cliente', '=', $request->filtroCliente);
        }

        if (isset($request->filtroAtendente) && $request->filtroAtendente != '._.') {
            $helpdesk = $helpdesk->where('pro_helpdesk.credencial_codigo_atendente', '=', $request->filtroAtendente);
        }

        if (!Gate::allows('helpdesk.ver_todos_chamados')) {
            $helpdesk = $helpdesk->where('pro_helpdesk.credencial_codigo_cliente', '=', Auth::user()->credencial_codigo);
        }

        $helpdesk = $helpdesk->orderBy('pro_prioridades.prioridade_grau', 'DESC');
        $helpdesk = $helpdesk->orderBy('pro_helpdesk.created_at', 'ASC');

        $helpdesk = $helpdesk->paginate(env('QTD_PAGINACAO'))->appends([
            'helpdesk_codigo' => $request->filtroNumero,
            'helpdesk_titulo' => $request->filtroTitulo,
            'categoria_codigo' => $request->filtroCategoria,
            'status_codigo' => $request->filtroStatus
        ]);

        $categorias = Categorias::get();
        $status     = Status::get();
        $clientes   = User::get();
        $atendentes = User::whereIn('perfil_codigo', [1,2])->get();

        if ($request->ajax()) {

            $retorno = [
                'dados' => $this->montaTabela($helpdesk),
                'links' => $helpdesk
            ];

            return response()->json($retorno);
        }

        return view('helpdesk.index', compact('categorias', 'status', 'clientes', 'atendentes'));
    }

    public function create()
    {
        $categorias    = Categorias::pluck('categoria_descricao', 'categoria_codigo');
        $departamentos = Departamentos::pluck('departamento_descricao', 'departamento_codigo');

        return view('helpdesk.create', compact('categorias', 'departamentos'));
    }

    public function store(Request $request)
    {
        try {

            $request['status_codigo'] = 1;
            $request['credencial_codigo_cliente'] = Auth::user()->credencial_codigo;

            $helpdesk = Helpdesk::create($request->all());

            if (isset($request->fotos)){
                for ($i = 0; $i < sizeof($request->fotos); $i++){
                    if ($request->fotos[$i] != null){
                        $file = $request->fotos[$i];

                        $file_name = $file->getClientOriginalName();

                        $file_path = storage_path('app/public/helpdesk/'.$helpdesk->helpdesk_codigo);

                        $helpdesk_anexos = [
                            'anexos_caminho' => $helpdesk->helpdesk_codigo.'/'.$file_name,
                            'helpdesk_codigo' => $helpdesk->helpdesk_codigo
                        ];

                        $anexos    = HelpdeskAnexos::create($helpdesk_anexos);

                        $file->move($file_path, $file_name);
                    }
                }
            }

            $response = [
                'message' => 'Chamado aberto com sucesso!',
                'data'    => $helpdesk->toArray(),
            ];

            if ($request->wantsJson()) {
                return response()->json($response);
            }

            return redirect()->route('helpdesk.index')->with('message', $response['message']);

        } catch (ValidatorException $e) {

            if ($request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    public function show($id)
    {
        $categorias = Categorias::pluck('categoria_descricao', 'categoria_codigo');
        $helpdesk   = Helpdesk::where('helpdesk_codigo', $id)->first();
        $anexos     = HelpdeskAnexos::where('helpdesk_codigo', $id)->get();
        $interacoes = HelpdeskInteracoes::where('helpdesk_codigo', $id)
                      ->leftJoin('sys_credencial', 'sys_credencial.credencial_codigo', '=', 'pro_helpdesk_interacoes.credencial_codigo')
                      ->orderBy('pro_helpdesk_interacoes.created_at', 'Desc')
                      ->get();

        return view('helpdesk.show', compact('helpdesk', 'categorias', 'anexos', 'interacoes'));
    }

    public function edit($id)
    {
        $departamentos = Departamentos::pluck('departamento_descricao', 'departamento_codigo');
        $helpdesk   = Helpdesk::where('helpdesk_codigo', $id)->leftJoin('pro_categorias', 'pro_helpdesk.categoria_codigo', '=', 'pro_categorias.categoria_codigo')->first();
        $imagens    = HelpdeskAnexos::where('helpdesk_codigo', $id)->get();

        $categorias = Categorias::where('departamento_codigo', $helpdesk->departamento_codigo)->pluck('categoria_descricao', 'categoria_codigo');

        if ($helpdesk->status_codigo == 4){
            return redirect('helpdesk')->withErrors('Não é permitido editar um chamado finalizado')->withInput();
        }

        return view('helpdesk.edit', compact('helpdesk', 'categorias', 'departamentos', 'imagens'));
    }

    public function update(Request $request, $id)
    {
        try {

            $update    = [
                'categoria_codigo' => $request->categoria_codigo,
                'helpdesk_titulo' => $request->helpdesk_titulo,
                'helpdesk_detalhes' => $request->helpdesk_detalhes
            ];

            $categoria = Helpdesk::where('helpdesk_codigo', $id)->update($update);

            $response  = [
                'message' => env('REGISTRO_ATUALIZADO'),
                'data'    => $categoria,
            ];

            if ($request->wantsJson()) {
                return response()->json($response);
            }

            if (isset($request->fotos)){
                for ($i = 0; $i < sizeof($request->fotos); $i++){
                    if ($request->fotos[$i] != null){
                        $file = $request->fotos[$i];

                        $file_name = $file->getClientOriginalName();

                        $file_path = storage_path('app/public/helpdesk/'.$id);

                        $helpdesk_anexos = [
                            'anexos_caminho' => $id.'/'.$file_name,
                            'helpdesk_codigo' => $id
                        ];

                        $anexos    = HelpdeskAnexos::create($helpdesk_anexos);

                        $file->move($file_path, $file_name);
                    }
                }
            }

            if (isset($request->fotos_remover)){
                for ($i = 0; $i < sizeof($request->fotos_remover); $i++){
                    $delete = HelpdeskAnexos::find($request->fotos_remover[$i])->delete();
                }
            }

resources/views/helpdesk/_form.blade.php
<div class="col-md-12">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group{{ $errors->has("departamento_codigo") ? ' has-error' : '' }}">
                {!! Form::label("departamento_codigo", 'Departamento', ['class' => '']) !!}
                {{ Form::select('departamento_codigo', $departamentos, null, ["class" => "form-control", 'id'=>'departamento_codigo', 'placeholder' => 'Selecione um Departamento','required', 'required']) }}
                <small class="text-danger">{{ $errors->first("departamento_codigo") }}</small>
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group{{ $errors->has("categoria_codigo") ? ' has-error' : '' }}">
                {!! Form::label("categoria_codigo", 'Categoria do Chamado', ['class' => '']) !!}
                {{ Form::select('categoria_codigo',  $categorias == [] ? [] : $categorias , null, ["class" => "form-control", 'id'=>'categoria_codigo', 'placeholder' => 'Selecione um Departamento','required', 'required' ]) }}
                <small class="text-danger">{{ $errors->first("categoria_codigo") }}</small>
            </div>
        </div>

        <div class="col-md-12">
            <div class="form-group{{ $errors->has("helpdesk_titulo") ? ' has-error' : '' }}">
                {!! Form::label("helpdesk_titulo", 'Título do Chamado', ['class' => '']) !!}
                {!! Form::text("helpdesk_titulo", null, ["class" => "form-control", 'id'=>'helpdesk_titulo', 'required','required', 'placeholder'=>'Informe uma título para o chamado'])  !!}
                <small class="text-danger">{{ $errors->first("helpdesk_titulo") }}</small>
            </div>
        </div>

        <div class="col-md-12">
            <div class="form-group{{ $errors->has("helpdesk_detalhes") ? ' has-error' : '' }}">
                {!! Form::label("helpdesk_detalhes", 'Título do Chamado', ['class' => '']) !!}
                {!! Form::textarea("helpdesk_detalhes", null, ["class" => "form-control", 'id'=>'helpdesk_detalhes', 'required','required', 'placeholder'=>'Descreva com clareza o problema'])  !!}
                <small class="text-danger">{{ $errors->first("helpdesk_detalhes") }}</small>
            </div>
        </div>

        <div class="col-md-12 div_files">
            <a class="btn btn-primary btn-add-file" style="color: #fff;"><i class="fas fa-plus"></i>  Inserir Arquivo</a>
        </div>

    </div>
</div>

resources/views/helpdesk/create.blade.php
@extends('layouts.app')

@section('titulo_pagina')
    <i class="fas fa-align-justify"></i> Cadastro de Chamado
@endsection

@section('conteudo')

    <!-- CARD CONTEÚDO -->
    <div class="card card-default cardConteudo">
        <div class="card-wrapper collapse show">
            <div class="card-body">
                {!! Form::open(['url'=>route('helpdesk.store'), 'id'=>'salvar-helpdesk', 'enctype'=>"multipart/form-data" ]) !!}
                    {{Form::token()}}
                    @include('helpdesk._form')
                    <button type="submit" class="btn btn-primary float-right mt-3 mr-3 mb-3"> <i class="fas fa-save"></i> Salvar </button>
                {!! Form::close() !!}
                <a href="{{ route('helpdesk.index') }}" class="btn btn-danger float-right mt-3 mr-3 mb-3"> <i class="fas fa-arrow-left"></i> Voltar </a>
            </div>
        </div>
    </div>
    <!-- FIM CARD CONTEÚDO -->
@endsection

@section('scripts')
    @include('helpdesk.script')

<script>
    $('.btn-add-file').click(function () {
        $('.div_files').append('<input type="file" class="form-control mt-3" name="fotos[]" multiple accept="image/x-png,image/gif,image/jpeg"/>');
    });
</script>


@endsection

resources/views/helpdesk/edit.blade.php
@extends('layouts.app')

@section('titulo_pagina')
    <i class="fas fa-align-justify"></i> Edição de Chamado - Nº {{ $helpdesk->helpdesk_codigo }}
@endsection

@section('conteudo')

    <!-- CARD CONTEÚDO -->
    <div class="card card-default cardConteudo">
        <div class="card-wrapper collapse show">
            <div class="card-body">
                {!! Form::model($helpdesk, ['route'=>['helpdesk.update', $helpdesk->helpdesk_codigo], 'method' => 'put','files' => true]) !!}
                {{Form::token()}}
                @include('helpdesk._form')


                <div class="col-md-12 mt-3">
                    <div class="row">
                        @if(isset($imagens))
                            @foreach ($imagens as $img)
                                <div class="col-md-2">
                                    <div class="card card-imagem" style="width:150px">
                                        <img class="card-img-top" src="{{ asset('storage/helpdesk/'.$img->anexos_caminho) }}" alt="Card image">
                                        <div class="card-body">
                                            <a class="btn btn-danger btn-rem-file" style="color: #fff;" data-id="{{ $img->anexos_codigo }}"><i class="fas fa-trash"></i> Remover</a>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        @endif
                    </div>
                </div>

                <button type="submit" class="btn btn-primary float-right mt-3 mr-3 mb-3"><i class="fas fa-save"></i>
                    Salvar
                </button>
                {!! Form::close() !!}
                <a href="{{ route('helpdesk.index') }}" class="btn btn-danger float-right mt-3 mr-3 mb-3"> <i
                        class="fas fa-arrow-left"></i> Voltar </a>
            </div>
        </div>
    </div>
    <!-- FIM CARD CONTEÚDO -->
@endsection

@section('scripts')
    @include('helpdesk.script')

    <script>
        $('.btn-add-file').click(function () {
            $('.div_files').append('<input type="file" class="form-control mt-3" name="fotos[]" multiple accept="image/x-png,image/gif,image/jpeg" />');
        })

        $('.btn-rem-file').click(function () {
            $('.div_files').append('<input type="text" class="form-control mt-3 hide" name="fotos_remover[]" value="' + $(this).attr('data-id') + '"/>');
            $(this).parents('.card-imagem').remove();
        })
    </script>

    @if(isset($helpdesk->categoria_codigo) && $helpdesk->categoria_departamento != '')
        <script>
            $('#categoria_codigo').val('{{ $helpdesk->categoria_codigo }}').change();
        </script>
    @endif
@endsection

resources/views/helpdesk/index.blade.php
@extends('layouts.app')

@section('titulo_pagina')
    <i class="fas fa-receipt"></i> Helpdesk
@endsection

@section('conteudo')

    <!-- CARD FILTROS -->
    <div class="card card-default">
        <div class="card-header">
            <a class="float-right" href="#" data-tool="card-collapse" data-toggle="tooltip">
                <em class="fa fa-plus"></em>
            </a>
            <div class="card-title" style="font-size: 12px;"><i class="fas fa-filter"></i>Filtros</div>
        </div>
        <div class="card-wrapper collapse">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="filtroNumero">Número</label>
                            <input type="number" class="form-control" name="filtroNumero" id="filtroNumero" min="0">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="filtroDescricao">Título</label>
                            <input type="text" class="form-control" name="filtroTitulo" id="filtroTitulo">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="filtroCategoria">Categoria</label>
                            <select class="form-control" name="filtroCategoria" id="filtroCategoria">
                                <option value="._.">Selecione Uma Categoria</option>
                                @foreach($categorias as $categoria)
                                    <option
                                        value="{{ $categoria->categoria_codigo }}">{{ $categoria->categoria_descricao }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="filtroStatus">Status</label>
                            <select class="form-control" name="filtroStatus" id="filtroStatus">
                                <option value="._.">Selecione Um Status</option>
                                @foreach($status as $status)
                                    <option
                                        value="{{ $status->status_codigo }}">{{ $status->status_descricao }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="filtroDataIni">Data de Abertura - Inicial</label>
                            <input type="date" class="form-control" name="filtroDataIni" id="filtroDataIni" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="filtroDataFim">Data de Abertura - Final</label>
                            <input type="date" class="form-control" name="filtroDataFim" id="filtroDataFim" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="filtroCliente">Cliente</label>
                            <select class="form-control" name="filtroCliente" id="filtroCliente">
                                <option value="._.">Selecione Um Cliente</option>
                                @foreach($clientes as $cliente)
                                    <option
                                        value="{{ $cliente->credencial_codigo }}">{{ $cliente->credencial_nome }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="filtroAtendente">Atendente</label>
                            <select class="form-control" name="filtroAtendente" id="filtroAtendente">
                                <option value="._.">Selecione Um Atendente</option>
                                @foreach($atendentes as $atendente)
                                    <option
                                        value="{{ $atendente->credencial_codigo }}">{{ $atendente->credencial_nome }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <button class="btn btn-primary btnPesquisa float-right mt-3 mb-3" value="Pesquisar"><i
                        class="fas fa-search"></i> Pesquisar
                </button>
            </div>
        </div>
    </div>
    <!-- FIM CARD FILTROS -->

    <!-- CARD CONTEÚDO -->
    <div class="card card-default cardConteudo">
        <div class="card-wrapper collapse show">
            <div class="card-body table-responsive">

                <div class="row">
                    <div class="col-md-2">
                        @can('helpdesk.create')
                            <a class="btn btn-primary float-left mb-2" href="{{ route('helpdesk.create') }}"><i
                                    class="fas fa-plus"></i> Novo Chamado </a>
                        @endcan
                    </div>
                </div>

                <table class="table table-sm table-bordered table-striped table-hover table-condensed tabela_helpdesk">
                    <thead>
                    <tr>
                        <th>Código</th>
                        <th>Data Abertura</th>
                        <th>Título</th>
                        <th>Usuário</th>
                        <th>Atendente</th>
                        <th>Status</th>

                        @if(Auth::user()->can('helpdesk.edit') || Auth::user()->can('helpdesk.destroy') || Auth::user()->can('helpdesk.show'))
                            <th colspan="100" style="min-width: 80px; max-width: 80px; width: 80px;">Ações</th>
                        @endif
                    </tr>
                    </thead>
                    <tbody></tbody>
                </table>
                <div class="float-right mt-5 links">

                </div>
            </div>
        </div>
    </div>
    <!-- FIM CARD CONTEÚDO -->
@endsection

@section('scripts')

    @include('helpdesk.script')

    <script>
        window.onload = setInterval("lista.do_buscar()", 60000);

        $(document).ready(function () {

            $('.btnPesquisa').click(function () {
                lista.do_buscar();
            });

            $('.btnPesquisa ').click();

        });
    </script>
@endsection

resources/views/helpdesk/script.blade.php
<script>

    $('#departamento_codigo').change(function () {
        create.do_buscar_categorias();
    });

var lista = {

    do_buscar: function(pagina = null){

        $('.cardConteudo').toggleClass('whirl');

        let params = '_token={{ csrf_token() }}';

        if ($('#filtroNumero').val() != '') {
            params += '&filtroNumero=' + $('#filtroNumero').val();
        }

        if ($('#filtroTitulo').val() != '') {
            params += '&filtroTitulo=' + $('#filtroTitulo').val();
        }

        if ($('#filtroCategoria').val() != '._.') {
            params += '&filtroCategoria=' + $('#filtroCategoria').val();
        }

        if ($('#filtroStatus').val() != '._.') {
            params += '&filtroStatus=' + $('#filtroStatus').val();
        }

        if ($('#filtroDataIni').val() != '._.') {
            params += '&filtroDataIni=' + $('#filtroDataIni').val();
        }

        if ($('#filtroDataFim').val() != '._.') {
            params += '&filtroDataFim=' + $('#filtroDataFim').val();
        }

        if ($('#filtroDataFim').val() != '._.') {
            params += '&filtroDataFim=' + $('#filtroDataFim').val();
        }

        if ($('#filtroCliente').val() != '._.') {
            params += '&filtroCliente=' + $('#filtroCliente').val();
        }

        if ($('#filtroAtendente').val() != '._.') {
            params += '&filtroAtendente=' + $('#filtroAtendente').val();
        }

        if (pagina != null){
            params += '&page='+pagina;
        }

        auxfn_do_ajax("{{route('helpdesk.index')}}", params, lista.do_alimenta_tabela, null);
    },

	do_alimenta_tabela: function(resposta){

        $('.tabela_helpdesk tbody').html(resposta.dados);

        lista.do_gerencia_paginacao(resposta.links);

        $('.cardConteudo').toggleClass('whirl');

        $('.btn-delete').click(function (event) {
            event.preventDefault();
            let form = $(this).parent('form');

            $.confirm({
                title: 'Desejas deletar este registro ?',
                content: 'Esta ação não poderá ser desfeita.',
                buttons: {
                    cancel: {
                        text: 'Cancelar'
                    },
                    somethingElse: {
                        text: 'Confirmar',
                        btnClass: 'btn-blue',
                        keys: ['enter', 'shift'],
                        action: function(){
                            form.submit();
                        }
                    }
                }
            });

        });
	},

    do_gerencia_paginacao: function (links) {
        if (typeof links != 'undefined'){
            let html = '<nav>';

            html += '<ul class="pagination">';
            html += '<li class="page-item prev" pagina="">';
                html += '<a class="page-link" aria-label="Previous"><span aria-hidden="true">&laquo;</span> <span class="sr-only">Previous</span></a>';
            html += '</li>';

            for (let i = 0; i < parseInt(links.last_page); i++){
                html += '<li class="page-item" pagina="'+ (i+1) +'"><a class="page-link">'+ (i+1) +'</a></li>';
            }

            html += '<li class="page-item next" pagina="">';
                html += '<a class="page-link" aria-label="Next"><span aria-hidden="true">&raquo;</span> <span class="sr-only">Next</span></a>';
            html += '</li>';
            html += '</ul>';

            $('.links').html(html);
            $('.page-item[pagina="'+links.current_page+'"]').addClass('active');

            $('.prev').attr('pagina', Number(links.current_page) - 1);
            $('.next').attr('pagina', Number(links.current_page) + 1);

            if (links.prev_page_url === null){
                $('.prev').attr('pagina', links.last_page);
            }

            if (links.current_page === links.last_page){
                $('.next').attr('pagina', 0);
            }

            $('.page-item').click(function () {
                lista.do_buscar($(this).attr('pagina'));
            });

        }
    }
};
    
var create = {
    do_buscar_categorias: function () {

        $('#categoria_codigo option').remove();

        if ($('#departamento_codigo').val() != '') {
            let params = '';

            params += 'departamento=' + $('#departamento_codigo').val();

            auxfn_do_ajax("{{ route('helpdesk.buscar_categorias') }}", params, create.do_alimenta_combo_categorias, null);
        }else{
            $('#categoria_codigo').append(new Option('Selecione um Departamento', ''));
        }
    },

    do_alimenta_combo_categorias: function (resposta) {
        if (resposta.length > 0){
            for (let i = 0; i < resposta.length; i++){
                $('#categoria_codigo').append(new Option(resposta[i].categoria_descricao, resposta[i].categoria_codigo));
            }
        }
    }
};
</script>