routes/web.php
<?php


Route::get('/', function () {
    if(Auth::guest())
    {
        return view('auth.login');
    }else{
        return redirect('/home');
    }
});

Auth::routes();

Route::group(['middleware' => ['auth', 'checkPermission']], function () {
    Route::get('/home',              'HomeController@index')->name('dashboard.index');
    Route::get('/getGraficos',       'HomeController@getGraficos')->name('dashboard.getGraficos');
    Route::resource('categorias',    'CategoriasController');
    Route::resource('helpdesk',      'HelpdeskController');
    Route::resource('empresas',      'EmpresasController');
    Route::resource('departamentos',  'DepartamentosController');
    Route::resource('perfilacesso',    'PerfisController');

    /* -------------------- HELPDESK -------------------- */
    Route::get('helpdesk/iniciarAtendimento/{id}', 'HelpdeskController@iniciarAtendimento')->name('helpdesk.iniciar_chamado');
    Route::get('helpdesk/finalizarAtendimento/{id}', 'HelpdeskController@finalizarAtendimento')->name('helpdesk.finalizar_chamado');
    Route::get('helpdesk/reabrirAtendimento/{id}', 'HelpdeskController@reabrirAtendimento')->name('helpdesk.reabrir_chamado');
    Route::post('helpdesk/inserirInteracao', 'HelpdeskController@inserirInteracao')->name('helpdesk.inserir_interacao');
    Route::get('buscarCategorias', 'HelpdeskController@buscarCategorias')->name('helpdesk.buscar_categorias');
});

app/Models/Departamentos.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Departamentos extends Model
{
    protected $table = 'pro_departamentos';
    protected $primaryKey = 'departamento_codigo';

    protected $fillable = [
        'departamento_descricao',
        'departamento_cor',
        'empresa_codigo'
    ];
}

app/Http/Controllers/DepartamentosController.php
<?php

namespace App\Http\Controllers;

use App\Models\Departamentos;
use App\Models\Empresas;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class DepartamentosController extends Controller
{

    public function index(Request $request)
    {
        $empresas    = Empresas::get();

        $departamentos     = new Departamentos();
        $departamentos     = $departamentos->join('pro_empresas', 'pro_departamentos.empresa_codigo', '=', 'pro_empresas.empresa_codigo');

        if (isset($request->filtroDescricao) && $request->filtroDescricao != '') {
            $departamentos = $departamentos->where('departamento_descricao', 'like', '%' . $request->filtroDescricao . '%');
        }

        if (isset($request->filtroPrioridade) && $request->filtroPrioridade != '._.') {
            $departamentos = $departamentos->where('pro_departamentos.empresa_codigo', $request->filtroPrioridade);
        }

        $departamentos     = $departamentos->paginate(env('QTD_PAGINACAO'))->appends([
            'departamento_descricao' => $request->filtroDescricao,
            'empresa_codigo' => $request->filtroPrioridade
        ]);

        if ($request->ajax()) {

            $retorno = [
                'dados' => $this->montaTabela($departamentos),
                'links' => $departamentos
            ];

            return response()->json($retorno);
        }

        return view('departamentos.index', compact('empresas'));
    }

    public function create()
    {
        $empresas = Empresas::pluck('empresa_rzsocial', 'empresa_codigo');

        return view('departamentos.create', compact('empresas'));
    }

    public function store(Request $request)
    {
        try {

            $departamento  = Departamentos::create($request->all());

            $response   = [
                'message' => env('REGISTRO_CADASTRADO'),
                'data'    => $departamento->toArray(),
            ];

            if ($request->wantsJson()) {
                return response()->json($response);
            }

            return redirect()->route('departamentos.index')->with('message', $response['message']);

        } catch (ValidatorException $e) {

            if ($request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    public function edit($id)
    {
        $empresas = Empresas::pluck('empresa_rzsocial', 'empresa_codigo');
        $departamento   = Departamentos::where('departamento_codigo', $id)->first();

        return view('departamentos.edit', compact('departamento', 'empresas'));
    }

    public function update(Request $request, $id)
    {
        try {

            $update     = [
                'departamento_descricao' => $request->departamento_descricao,
                'empresa_codigo' => $request->empresa_codigo,
                'departamento_cor' => $request->departamento_cor,
            ];

            $departamento  = Departamentos::where('departamento_codigo', $id)->update($update);

            $response   = [
                'message' => env('REGISTRO_ATUALIZADO'),
                'data'    => $departamento,
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->route('departamentos.index')->with('message', $response['message']);

        } catch (ValidatorException $e) {

            if ($request->wantsJson()) {

                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    public function destroy($id)
    {
        $deleted = Departamentos::find($id)->delete();

        if (request()->wantsJson()) {

            return response()->json([
                'message' => env('REGISTRO_DELETADO'),
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', env('REGISTRO_DELETADO'));
    }

    public function montaTabela($registros)
    {
        $html = '';

        if (sizeof($registros) > 0) {
            for ($i = 0; $i < sizeof($registros); $i++) {
                $html .= '<tr>';
                $html .= '<td>' . $registros[$i]['departamento_codigo'] . '</td>';
                $html .= '<td>' . $registros[$i]['departamento_descricao'] . '</td>';
                $html .= '<td>' . $registros[$i]['empresa_rzsocial'] . '</td>';

                if (Gate::allows('departamentos.edit')) {
                    $html .= '<td><a href="'.route('departamentos.edit', $registros[$i]['departamento_codigo']).'" class="btn btn-warning btn-sm" style="width: 40px;"><i class="fa fa-edit"></i></a ></td>';
                }

                if (Gate::allows('departamentos.destroy')) {
                    $html .= '<td>';
                    $html .= '<form method="POST" action="'.route( 'departamentos.destroy', $registros[$i]['departamento_codigo']).'">';
                    $html .= csrf_field();
                    $html .= method_field('DELETE');
                    $html .= '<button type="submit" class="btn btn-danger btn-sm btn-delete" style="width: 40px;"> <i class="fa fa-trash"></i> </button>';
                    $html .= '</form>';
                    $html .= '</td>';
                }

                $html .= '</tr>';
            }
        } else {
            $html .= '<tr>';
            $html .= '<td colspan="5">Nenhum registro a exibir</td>';
            $html .= '</tr>';
        }

        return $html;
    }

}

resources/views/departamentos/_form.blade.php
<div class="col-md-12">
    <div class="row">
        <div class="col-md-12">
            <div class="form-group{{ $errors->has("departamento_descricao") ? ' has-error' : '' }}">
                {!! Form::label("departamento_descricao", 'Descrição', ['class' => '']) !!}
                {!! Form::text("departamento_descricao", null, ["class" => "form-control", 'id'=>'departamento_descricao', 'required','required', 'placeholder'=>"Informe uma descrição para o departamento"])  !!}
                <small class="text-danger">{{ $errors->first("departamento_descricao") }}</small>
            </div>
        </div>

        <div class="col-md-12">
            <div class="form-group{{ $errors->has("empresa_codigo") ? ' has-error' : '' }}">
                {!! Form::label("empresa_codigo", 'Empresa', ['class' => '']) !!}
                {{ Form::select('empresa_codigo', $empresas, null, ["class" => "form-control", 'id'=>'empresa_codigo', 'required', 'required']) }}
                <small class="text-danger">{{ $errors->first("empresa_codigo") }}</small>
            </div>
        </div>

        <div class="col-md-12">
            <div class="form-group{{ $errors->has("departamento_cor") ? ' has-error' : '' }}">
                {!! Form::label("departamento_cor", 'Cor nos gráficos', ['class' => '']) !!}
                {{ Form::color('departamento_cor', null, ["class" => "form-control", 'id'=>'departamento_cor', 'required', 'required']) }}
                <small class="text-danger">{{ $errors->first("departamento_cor") }}</small>
            </div>
        </div>
    </div>
</div>

resources/views/departamentos/create.blade.php
@extends('layouts.app')

@section('titulo_pagina')
    <i class="fas fa-boxes"></i> Cadastro de Departamentos
@endsection

@section('conteudo')

    <!-- CARD CONTEÚDO -->
    <div class="card card-default cardConteudo">
        <div class="card-wrapper collapse show">
            <div class="card-body">
                {!! Form::open(['url'=>route('departamentos.store'), 'id'=>'salvar-categoria' ]) !!}
                    {{Form::token()}}
                    @include('departamentos._form')
                    <button type="submit" class="btn btn-primary float-right mt-3 mr-3 mb-3"> <i class="fas fa-save"></i> Salvar </button>
                {!! Form::close() !!}
                <a href="{{ route('departamentos.index') }}" class="btn btn-danger float-right mt-3 mr-3 mb-3"> <i class="fas fa-arrow-left"></i> Voltar </a>
            </div>
        </div>
    </div>
    <!-- FIM CARD CONTEÚDO -->
@endsection

@section('scripts')
    @include('categorias.script')
@endsection

resources/views/departamentos/edit.blade.php
@extends('layouts.app')

@section('titulo_pagina')
    <i class="fas fa-boxes"></i> Edição de Departamento - {{ $departamento->departamento_descricao }}
@endsection

@section('conteudo')

    <!-- CARD CONTEÚDO -->
    <div class="card card-default cardConteudo">
        <div class="card-wrapper collapse show">
            <div class="card-body">
                {!! Form::model($departamento, ['route'=>['departamentos.update', $departamento->departamento_codigo], 'method' => 'put','files' => true]) !!}
                    {{Form::token()}}
                    @include('departamentos._form')
                    <button type="submit" class="btn btn-primary float-right mt-3 mr-3 mb-3"> <i class="fas fa-save"></i> Salvar </button>
                {!! Form::close() !!}
                    <a href="{{ route('departamentos.index') }}" class="btn btn-danger float-right mt-3 mr-3 mb-3"> <i class="fas fa-arrow-left"></i> Voltar </a>
            </div>
        </div>
    </div>
    <!-- FIM CARD CONTEÚDO -->
@endsection

@section('scripts')
    @include('categorias.script')
@endsection

resources/views/departamentos/index.blade.php
@extends('layouts.app')

@section('titulo_pagina')
    <i class="fas fa-boxes"></i> Departamentos
@endsection

@section('conteudo')

    <!-- CARD FILTROS -->
    <div class="card card-default">
        <div class="card-header">
            <a class="float-right" href="#" data-tool="card-collapse" data-toggle="tooltip">
                <em class="fa fa-plus"></em>
            </a>
            <div class="card-title" style="font-size: 12px;"><i class="fas fa-filter"></i>Filtros</div>
        </div>
        <div class="card-wrapper collapse">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="filtroDescricao">Descrição</label>
                            <input type="text" class="form-control" name="filtroDescricao" id="filtroDescricao">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="filtroEmpresa">Empresa</label>
                            <select class="form-control" name="filtroEmpresa" id="filtroEmpresa">
                                <option value="._.">Selecione Uma Empresa</option>
                                @foreach($empresas as $empresa)
                                    <option
                                        value="{{ $empresa->empresa_codigo }}">{{ $empresa->empresa_rzsocial }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <button class="btn btn-primary btnPesquisa float-right mt-3 mb-3" value="Pesquisar"><i
                        class="fas fa-search"></i> Pesquisar
                </button>
            </div>
        </div>
    </div>
    <!-- FIM CARD FILTROS -->

    <!-- CARD CONTEÚDO -->
    <div class="card card-default cardConteudo">
        <div class="card-wrapper collapse show">
            <div class="card-body table-responsive">

                @can('departamentos.create')
                    <a class="btn btn-primary float-left mb-2" href="{{ route('departamentos.create') }}"><i
                            class="fas fa-plus"></i> Novo Departamento </a>
                @endcan

                <table class="table table-sm table-bordered table-striped table-hover tabela_categorias">
                    <thead>
                    <tr>
                        <th>Código</th>
                        <th>Descrição</th>
                        <th>Empresa</th>
                        @if(Auth::user()->can('departamentos.edit') || Auth::user()->can('departamentos.destroy'))
                            <th colspan="100">Ações</th>
                        @endif
                    </tr>
                    </thead>
                    <tbody></tbody>
                </table>
                <div class="float-right mt-5 links">

                </div>
            </div>
        </div>
    </div>
    <!-- FIM CARD CONTEÚDO -->
@endsection

@section('scripts')

    @include('departamentos.script')

    <script>
        $(document).ready(function () {

            $('.btnPesquisa').click(function () {
                lista.do_buscar();
            });

            $('.btnPesquisa ').click();

        });
    </script>
@endsection

resources/views/departamentos/script.blade.php
<script>
var lista = {

    do_buscar: function(pagina = null){

        $('.cardConteudo').toggleClass('whirl');

        let params = '_token={{ csrf_token() }}';

        if ($('#filtroDescricao').val() != '') {
            params += '&filtroDescricao=' + $('#filtroDescricao').val();
        }

        if ($('#filtroEmpresa').val() != '._.') {
            params += '&filtroPrioridade=' + $('#filtroPrioridade').val();
        }

        if (pagina != null){
            params += '&page='+pagina;
        }

        auxfn_do_ajax("{{route('departamentos.index')}}", params, lista.do_alimenta_tabela, null);
    },

	do_alimenta_tabela: function(resposta){

			$('.tabela_categorias tbody').html(resposta.dados);

            lista.do_gerencia_paginacao(resposta.links);

            $('.cardConteudo').toggleClass('whirl');

        $('.btn-delete').click(function (event) {
            event.preventDefault();
            let form = $(this).parent('form');

            $.confirm({
                title: 'Desejas deletar este registro ?',
                content: 'Esta ação não poderá ser desfeita.',
                buttons: {
                    cancel: {
                        text: 'Cancelar'
                    },
                    somethingElse: {
                        text: 'Confirmar',
                        btnClass: 'btn-blue',
                        keys: ['enter', 'shift'],
                        action: function(){
                            form.submit();
                        }
                    }
                }
            });

        });
	},

    do_gerencia_paginacao: function (links) {
        if (typeof links != 'undefined'){
            let html = '<nav>';

            html += '<ul class="pagination">';
            html += '<li class="page-item prev" pagina="">';
                html += '<a class="page-link" aria-label="Previous"><span aria-hidden="true">&laquo;</span> <span class="sr-only">Previous</span></a>';
            html += '</li>';

            for (let i = 0; i < parseInt(links.last_page); i++){
                html += '<li class="page-item" pagina="'+ (i+1) +'"><a class="page-link">'+ (i+1) +'</a></li>';
            }

            html += '<li class="page-item next" pagina="">';
                html += '<a class="page-link" aria-label="Next"><span aria-hidden="true">&raquo;</span> <span class="sr-only">Next</span></a>';
            html += '</li>';
            html += '</ul>';

            $('.links').html(html);
            $('.page-item[pagina="'+links.current_page+'"]').addClass('active');

            $('.prev').attr('pagina', Number(links.current_page) - 1);
            $('.next').attr('pagina', Number(links.current_page) + 1);

            if (links.prev_page_url === null){
                $('.prev').attr('pagina', links.last_page);
            }

            if (links.current_page === links.last_page){
                $('.next').attr('pagina', 0);
            }

            $('.page-item').click(function () {
                lista.do_buscar($(this).attr('pagina'));
            });

        }
    }
}



</script>