routes/web.php
<?php


Route::get('/', function () {
    if(Auth::guest())
    {
        return view('auth.login');
    }else{
        return redirect('/home');
    }
});

Auth::routes();

Route::group(['middleware' => ['auth', 'checkPermission']], function () {
    Route::get('/home',              'HomeController@index')->name('dashboard.index');
    Route::get('/getGraficos',       'HomeController@getGraficos')->name('dashboard.getGraficos');
    Route::resource('categorias',    'CategoriasController');
    Route::resource('helpdesk',      'HelpdeskController');
    Route::resource('empresas',      'EmpresasController');
    Route::resource('departamentos',  'DepartamentosController');
    Route::resource('perfilacesso',    'PerfisController');

    /* -------------------- HELPDESK -------------------- */
    Route::get('helpdesk/iniciarAtendimento/{id}', 'HelpdeskController@iniciarAtendimento')->name('helpdesk.iniciar_chamado');
    Route::get('helpdesk/finalizarAtendimento/{id}', 'HelpdeskController@finalizarAtendimento')->name('helpdesk.finalizar_chamado');
    Route::get('helpdesk/reabrirAtendimento/{id}', 'HelpdeskController@reabrirAtendimento')->name('helpdesk.reabrir_chamado');
    Route::post('helpdesk/inserirInteracao', 'HelpdeskController@inserirInteracao')->name('helpdesk.inserir_interacao');
    Route::get('buscarCategorias', 'HelpdeskController@buscarCategorias')->name('helpdesk.buscar_categorias');
});

app/Models/Categorias.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Categorias extends Model
{
    protected $table = 'pro_categorias';
    protected $primaryKey = 'categoria_codigo';

    protected $fillable = [
        'categoria_descricao',
        'departamento_codigo',
        'prioridade_codigo',
        'categoria_cor'
    ];

    public function prioridade(){
        return $this->belongsTo(Prioridades::class, 'prioridade_codigo', '');
    }
}

app/Http/Controllers/CategoriasController.php
<?php

namespace App\Http\Controllers;

use App\Models\Categorias;
use App\Models\Departamentos;
use App\Models\Prioridades;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class CategoriasController extends Controller
{

    public function index(Request $request)
    {
        $prioridades    = Prioridades::get();
        $categorias     = new Categorias();
        $categorias     = $categorias->join('pro_prioridades', 'pro_categorias.prioridade_codigo', '=', 'pro_prioridades.prioridade_codigo');
        $categorias     = $categorias->leftJoin('pro_departamentos', 'pro_categorias.departamento_codigo', '=', 'pro_departamentos.departamento_codigo');

        if (isset($request->filtroDescricao) && $request->filtroDescricao != '') {
            $categorias = $categorias->where('categoria_descricao', 'like', '%' . $request->filtroDescricao . '%');
        }

        if (isset($request->filtroPrioridade) && $request->filtroPrioridade != '._.') {
            $categorias = $categorias->where('pro_categorias.prioridade_codigo', $request->filtroPrioridade);
        }

        $categorias     = $categorias->paginate(env('QTD_PAGINACAO'))->appends([
            'categoria_descricao' => $request->filtroDescricao,
            'prioridade_codigo' => $request->filtroPrioridade
        ]);


        if ($request->ajax()) {

            $retorno = [
                'dados' => $this->montaTabela($categorias),
                'links' => $categorias
            ];

            return response()->json($retorno);
        }

        return view('categorias.index', compact('prioridades'));
    }

    public function create()
    {
        $departamentos = Departamentos::pluck('departamento_descricao', 'departamento_codigo');
        $prioridades   = Prioridades::pluck('prioridade_descricao', 'prioridade_codigo');

        return view('categorias.create', compact('prioridades','departamentos'));
    }

    public function store(Request $request)
    {
        try {

            $categoria  = Categorias::create($request->all());

            $response   = [
                'message' => env('REGISTRO_CADASTRADO'),
                'data'    => $categoria->toArray(),
            ];

            if ($request->wantsJson()) {
                return response()->json($response);
            }

            return redirect()->route('categorias.index')->with('message', $response['message']);

        } catch (ValidatorException $e) {

            if ($request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    public function edit($id)
    {
        $departamentos = Departamentos::pluck('departamento_descricao', 'departamento_codigo');
        $prioridades = Prioridades::pluck('prioridade_descricao', 'prioridade_codigo');
        $categoria   = Categorias::where('categoria_codigo', $id)->first();

        return view('categorias.edit', compact('categoria', 'prioridades', 'departamentos'));
    }

    public function update(Request $request, $id)
    {
        try {

            $update     = [
                'categoria_descricao' => $request->categoria_descricao,
                'departamento_codigo' => $request->departamento_codigo,
                'prioridade_codigo' => $request->prioridade_codigo,
                'categoria_cor' => $request->categoria_cor
            ];

            $categoria  = Categorias::where('categoria_codigo', $id)->update($update);

            $response   = [
                'message' => env('REGISTRO_ATUALIZADO'),
                'data'    => $categoria,
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->route('categorias.index')->with('message', $response['message']);

        } catch (ValidatorException $e) {

            if ($request->wantsJson()) {

                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    public function destroy($id)
    {
        $deleted = Categorias::find($id)->delete();

        if (request()->wantsJson()) {

            return response()->json([
                'message' => env('REGISTRO_DELETADO'),
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', env('REGISTRO_DELETADO'));
    }

    public function montaTabela($registros)
    {
        $html = '';

        if (sizeof($registros) > 0) {
            for ($i = 0; $i < sizeof($registros); $i++) {
                $html .= '<tr>';
                $html .= '<td>' . $registros[$i]['categoria_codigo'] . '</td>';
                $html .= '<td>' . $registros[$i]['categoria_descricao'] . '</td>';
                $html .= '<td>' . $registros[$i]['departamento_descricao'] . '</td>';
                $html .= '<td>' . $registros[$i]['prioridade_descricao'] . '</td>';

                if (Gate::allows('categorias.edit')) {
                    $html .= '<td><a href="'.route('categorias.edit', $registros[$i]['categoria_codigo']).'" class="btn btn-warning btn-sm" style="width: 40px;"><i class="fa fa-edit"></i></a ></td>';
                }

                if (Gate::allows('categorias.destroy')) {
                    $html .= '<td>';
                    $html .= '<form method="POST" action="'.route( 'categorias.destroy', $registros[$i]['categoria_codigo']).'">';
                    $html .= csrf_field();
                    $html .= method_field('DELETE');
                    $html .= '<button type="submit" class="btn btn-danger btn-sm btn-delete" style="width: 40px;"> <i class="fa fa-trash"></i> </button>';
                    $html .= '</form>';
                    $html .= '</td>';
                }

                $html .= '</tr>';
            }
        } else {
            $html .= '<tr>';
            $html .= '<td colspan="5">Nenhum registro a exibir</td>';
            $html .= '</tr>';
        }

        return $html;
    }

}

resources/views/categorias/_form.blade.php
<div class="col-md-12">
    <div class="row">
        <div class="col-md-12">
            <div class="form-group{{ $errors->has("categoria_descricao") ? ' has-error' : '' }}">
                {!! Form::label("categoria_descricao", 'Descrição', ['class' => '']) !!}
                {!! Form::text("categoria_descricao", null, ["class" => "form-control", 'id'=>'categoria_descricao', 'required','required', 'placeholder'=>"Informe uma descrição para a categoria"])  !!}
                <small class="text-danger">{{ $errors->first("categoria_descricao") }}</small>
            </div>
        </div>

        <div class="col-md-12">
            <div class="form-group{{ $errors->has("departamento_codigo") ? ' has-error' : '' }}">
                {!! Form::label("departamento_codigo", 'Departamento', ['class' => '']) !!}
                {{ Form::select('departamento_codigo', $departamentos, null, ["class" => "form-control", 'id'=>'departamento_codigo']) }}
                <small class="text-danger">{{ $errors->first("departamento_codigo") }}</small>
            </div>
        </div>

        <div class="col-md-12">
            <div class="form-group{{ $errors->has("prioridade_codigo") ? ' has-error' : '' }}">
                {!! Form::label("prioridade_codigo", 'Prioridade', ['class' => '']) !!}
                {{ Form::select('prioridade_codigo', $prioridades, null, ["class" => "form-control", 'id'=>'prioridade_codigo', 'required', 'required']) }}
                <small class="text-danger">{{ $errors->first("prioridade_codigo") }}</small>
            </div>
        </div>

        <div class="col-md-12">
            <div class="form-group{{ $errors->has("categoria_cor") ? ' has-error' : '' }}">
                {!! Form::label("categoria_cor", 'Cor nos gráficos', ['class' => '']) !!}
                {{ Form::color('categoria_cor', null, ["class" => "form-control", 'id'=>'categoria_cor', 'required', 'required']) }}
                <small class="text-danger">{{ $errors->first("categoria_cor") }}</small>
            </div>
        </div>
    </div>
</div>

resources/views/categorias/create.blade.php
@extends('layouts.app')

@section('titulo_pagina')
    <i class="fas fa-align-justify"></i> Cadastro de Categoria
@endsection

@section('conteudo')

    <!-- CARD CONTEÚDO -->
    <div class="card card-default cardConteudo">
        <div class="card-wrapper collapse show">
            <div class="card-body">
                {!! Form::open(['url'=>route('categorias.store'), 'id'=>'salvar-categoria' ]) !!}
                    {{Form::token()}}
                    @include('categorias._form')
                    <button type="submit" class="btn btn-primary float-right mt-3 mr-3 mb-3"> <i class="fas fa-save"></i> Salvar </button>
                {!! Form::close() !!}
                <a href="{{ route('categorias.index') }}" class="btn btn-danger float-right mt-3 mr-3 mb-3"> <i class="fas fa-arrow-left"></i> Voltar </a>
            </div>
        </div>
    </div>
    <!-- FIM CARD CONTEÚDO -->
@endsection

@section('scripts')
    @include('categorias.script')
@endsection

resources/views/categorias/edit.blade.php
@extends('layouts.app')

@section('titulo_pagina')
    <i class="fas fa-align-justify"></i> Edição de Categoria - {{ $categoria->categoria_descricao }}
@endsection

@section('conteudo')

    <!-- CARD CONTEÚDO -->
    <div class="card card-default cardConteudo">
        <div class="card-wrapper collapse show">
            <div class="card-body">
                {!! Form::model($categoria, ['route'=>['categorias.update', $categoria->categoria_codigo], 'method' => 'put','files' => true]) !!}
                    {{Form::token()}}
                    @include('categorias._form')
                    <button type="submit" class="btn btn-primary float-right mt-3 mr-3 mb-3"> <i class="fas fa-save"></i> Salvar </button>
                {!! Form::close() !!}
                    <a href="{{ route('categorias.index') }}" class="btn btn-danger float-right mt-3 mr-3 mb-3"> <i class="fas fa-arrow-left"></i> Voltar </a>
            </div>
        </div>
    </div>
    <!-- FIM CARD CONTEÚDO -->
@endsection

@section('scripts')
    @include('categorias.script')
@endsection

resources/views/categorias/index.blade.php
@extends('layouts.app')

@section('titulo_pagina')
    <i class="fas fa-align-justify"></i> Categorias de Chamados
@endsection

@section('conteudo')

    <!-- CARD FILTROS -->
    <div class="card card-default">
        <div class="card-header">
            <a class="float-right" href="#" data-tool="card-collapse" data-toggle="tooltip">
                <em class="fa fa-plus"></em>
            </a>
            <div class="card-title" style="font-size: 12px;"><i class="fas fa-filter"></i>Filtros</div>
        </div>
        <div class="card-wrapper collapse">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="filtroDescricao">Descrição</label>
                            <input type="text" class="form-control" name="filtroDescricao" id="filtroDescricao">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="filtroPrioridade">Prioridade</label>
                            <select class="form-control" name="filtroPrioridade" id="filtroPrioridade">
                                <option value="._.">Selecione Uma Prioridade</option>
                                @foreach($prioridades as $prioridade)
                                    <option
                                        value="{{ $prioridade->prioridade_codigo }}">{{ $prioridade->prioridade_descricao }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <button class="btn btn-primary btnPesquisa float-right mt-3 mb-3" value="Pesquisar"><i
                        class="fas fa-search"></i> Pesquisar
                </button>
            </div>
        </div>
    </div>
    <!-- FIM CARD FILTROS -->

    <!-- CARD CONTEÚDO -->
    <div class="card card-default cardConteudo">
        <div class="card-wrapper collapse show">
            <div class="card-body table-responsive">

                @can('categorias.create')
                    <a class="btn btn-primary float-left mb-2" href="{{ route('categorias.create') }}"><i
                            class="fas fa-plus"></i> Nova Categoria </a>
                @endcan

                <table class="table table-sm table-bordered table-striped table-hover tabela_categorias">
                    <thead>
                    <tr>
                        <th>Código</th>
                        <th>Descrição</th>
                        <th>Departamento</th>
                        <th>Prioridade</th>
                        @if(Auth::user()->can('categorias.edit') || Auth::user()->can('categorias.destroy'))
                            <th colspan="100">Ações</th>
                        @endif
                    </tr>
                    </thead>
                    <tbody></tbody>
                </table>
                <div class="float-right mt-5 links">

                </div>
            </div>
        </div>
    </div>
    <!-- FIM CARD CONTEÚDO -->
@endsection

@section('scripts')

    @include('categorias.script')

    <script>
        $(document).ready(function () {

            $('.btnPesquisa').click(function () {
                lista.do_buscar();
            });

            $('.btnPesquisa ').click();

        });
    </script>
@endsection

resources/views/categorias/script.blade.php
<script>
var lista = {

    do_buscar: function(pagina = null){

        $('.cardConteudo').toggleClass('whirl');

        let params = '_token={{ csrf_token() }}';

        if ($('#filtroDescricao').val() != '') {
            params += '&filtroDescricao=' + $('#filtroDescricao').val();
        }

        if ($('#filtroPrioridade').val() != '._.') {
            params += '&filtroPrioridade=' + $('#filtroPrioridade').val();
        }

        if (pagina != null){
            params += '&page='+pagina;
        }

        auxfn_do_ajax("{{route('categorias.index')}}", params, lista.do_alimenta_tabela, null);
    },

	do_alimenta_tabela: function(resposta){

			$('.tabela_categorias tbody').html(resposta.dados);

            lista.do_gerencia_paginacao(resposta.links);

            $('.cardConteudo').toggleClass('whirl');

        $('.btn-delete').click(function (event) {
            event.preventDefault();
            let form = $(this).parent('form');

            $.confirm({
                title: 'Desejas deletar este registro ?',
                content: 'Esta ação não poderá ser desfeita.',
                buttons: {
                    cancel: {
                        text: 'Cancelar'
                    },
                    somethingElse: {
                        text: 'Confirmar',
                        btnClass: 'btn-blue',
                        keys: ['enter', 'shift'],
                        action: function(){
                            form.submit();
                        }
                    }
                }
            });

        });
	},

    do_gerencia_paginacao: function (links) {
        if (typeof links != 'undefined'){
            let html = '<nav>';

            html += '<ul class="pagination">';
            html += '<li class="page-item prev" pagina="">';
                html += '<a class="page-link" aria-label="Previous"><span aria-hidden="true">&laquo;</span> <span class="sr-only">Previous</span></a>';
            html += '</li>';

            for (let i = 0; i < parseInt(links.last_page); i++){
                html += '<li class="page-item" pagina="'+ (i+1) +'"><a class="page-link">'+ (i+1) +'</a></li>';
            }

            html += '<li class="page-item next" pagina="">';
                html += '<a class="page-link" aria-label="Next"><span aria-hidden="true">&raquo;</span> <span class="sr-only">Next</span></a>';
            html += '</li>';
            html += '</ul>';

            $('.links').html(html);
            $('.page-item[pagina="'+links.current_page+'"]').addClass('active');

            $('.prev').attr('pagina', Number(links.current_page) - 1);
            $('.next').attr('pagina', Number(links.current_page) + 1);

            if (links.prev_page_url === null){
                $('.prev').attr('pagina', links.last_page);
            }

            if (links.current_page === links.last_page){
                $('.next').attr('pagina', 0);
            }

            $('.page-item').click(function () {
                lista.do_buscar($(this).attr('pagina'));
            });

        }
    }
}



</script>